### PR TITLE
fix(useModal): `card` preset without corresponding props in `n-card` slots

### LINKED ISSUE #5746: useModal 预设为card时不能展示content
### 描述错误

useModal预设为card时配置content不能显示，style样式也无效。

### 复现步骤

``` ts
 const modalInst = modal.create({
        title: "模态框",
        preset: "card",
        style: { width: "300px" },
        content: () =>
          h(Fragment, null, {
            default: () => "Hello World",
            footer: () =>
              h(NFlex, null, [
                h(NButton, null, "取消"),
                h(
                  NButton,
                  {
                    type: "primary",
                  },
                  "确认"
                ),
              ]),
          }),
      });
```

### 最小复现链接

https://codesandbox.io/p/sandbox/festive-scott-vg3hfp

### 系统信息

```Shell
MacOS 13.4 (22F66)
Chrome 122.0.6261.94
naive-ui 2.38.1
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

### PR DESCRIPTION
**Pull request by jizai1125**
closes #5746

### CODE REVIEW

File: src/card/src/Card.tsx [hunk 1]
```diff
@@ -216,55 +231,60 @@ export default defineComponent({
...
-            >
+        {resolveWrappedVNode(
+          resolveSlot($slots.header, () => [render(this.title)]),
+          (children) => {
+            return children || this.closable ? (
               <div
-                class={`${mergedClsPrefix}-card-header__main`}
-                role="heading"
+                class={[`${mergedClsPrefix}-card-header`, this.headerClass]}
+                style={this.headerStyle}
```
Comment (07akioni) [inline src/card/src/Card.tsx:249]:
```suggestion
                style={this.headerStyle}
                role="heading"
```
