### PR TITLE
fix(input): `on-keyup` prop type

### LINKED ISSUE #5101: Getting a warning when passing multiple @keyup.x handlers on n-input
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(114.0.5735.198)

### System and its version (系统及其版本)
MacOS(12.6.7)

### Node version (Node 版本)
v19.5.0

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/distracted-mclean-rtd5kl

### Reappearance steps (重现步骤)
add n-input element with more then one @keyup handler, for example: 
```
<n-input
    @keyup.enter="handleInput"
    @keyup.up="handleUpKey"
    @keyup.down="handleDownKey"
  />
```

### Expected results (期望的结果)
No warning should appear in console.

### Actual results (实际的结果)
Getting this warning multiple times, each time the event triggers:
`[Vue warn]: Invalid prop: type check failed for prop "onKeyup". Expected Function, got Array`

### PR DESCRIPTION
**Pull request by jizai1125**
closes #5101

### CODE REVIEW

File: src/input/src/Input.tsx [hunk 1]
```diff
@@ -174,6 +174,7 @@ export default defineComponent({
   name: 'Input',
   props: inputProps,
   setup (props) {
+    console.log(props)
```
Comment (amadeus711) [inline src/input/src/Input.tsx:177]: fix

**Review by amadeus711 — CHANGES_REQUESTED** [review]
