### PR TITLE
fix(input): click clear icon to trigger twice

### LINKED ISSUE #5510: input组件在进行clear操作时会执行两次
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.0-rc.3

### Browser and its version (浏览器及其版本)
Google Chrome(120.0.6099.130)

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
16.20

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/epic-maxwell-339rgg?file=%2Fsrc%2FDemo.vue%3A27%2C28

### Reappearance steps (重现步骤)
1.在输入框随便输入内容
2.点击清空图标
3.打开开发者模式观看控制台

### Expected results (期望的结果)
控制台打印一次 "clear"

### Actual results (实际的结果)
控制台打印两次 "clear"

### PR DESCRIPTION
**Pull request by Volankey**
close #5510

### CODE REVIEW

File: src/_internal/clear/src/Clear.tsx [hunk 1]
```diff
@@ -36,7 +36,6 @@ export default defineComponent({
                 <div
                   key="dismiss"
                   class={`${clsPrefix}-base-clear__clear`}
-                  onClick={this.onClear}
                   onMousedown={this.handleMouseDown}
```
Comment (OrbisK) [inline src/_internal/clear/src/Clear.tsx:39]: Maybe just my opinion but I would go for the click rather than the mouse down. The mousedown has no consistent behavior when it comes to touch displays, and many more pitfalls.

**Review by OrbisK — CHANGES_REQUESTED** [review]

File: src/_internal/clear/src/Clear.tsx (hunk 1 above)
Comment (Volankey) [reply src/_internal/clear/src/Clear.tsx:39]: https://github.com/tusen-ai/naive-ui/commit/5094c407cf220421afa3ef79841f0150e08ed46b
Maybe you should see this commit.

Comment (OrbisK) [reply src/_internal/clear/src/Clear.tsx:39]: Okay, I get the point. 

However, I wonder if there isn't a better alternative in both cases, especially as in both cases the focus should be on the input afterwards.

Thanks anyway 😄

**Comment by 07akioni** [comment]
#5532 has some problem. I fixed it in another way. Seems the link issue currently doesn't exist.
